
project_id = "ndhakvhrrkczgylcmyoc"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000"]
jwt_expiry = 604800
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true

[realtime]
enabled = true

[analytics]
enabled = false

[functions.ai-chatbot]
verify_jwt = true

[functions.financial-news]
verify_jwt = true

[functions.generate-insight]
verify_jwt = true

[functions.stock-data]
verify_jwt = true

[functions.takbull-payment]
verify_jwt = true

[functions.takbull-payment.import_map]
imports = { "serve" = "https://deno.land/std@0.168.0/http/server.ts" }

[functions.takbull-webhook]
verify_jwt = false

[functions.takbull-webhook.import_map]
imports = { "serve" = "https://deno.land/std@0.168.0/http/server.ts", "@supabase/supabase-js" = "https://esm.sh/@supabase/supabase-js@2.7.1" }

[functions.izidoc-sign]
verify_jwt = true

[functions.izidoc-sign.import_map]
imports = { "serve" = "https://deno.land/std@0.168.0/http/server.ts", "@supabase/supabase-js" = "https://esm.sh/@supabase/supabase-js@2.7.1" }

[functions.gmail-sender]
verify_jwt = true

[functions.gmail-sender.import_map]
imports = { "serve" = "https://deno.land/std@0.168.0/http/server.ts", "@supabase/supabase-js" = "https://esm.sh/@supabase/supabase-js@2.7.1", "googleapis" = "https://esm.sh/googleapis@126.0.1" }

[functions.test-gmail]
verify_jwt = false

[functions.test-gmail.import_map]
imports = { "serve" = "https://deno.land/std@0.168.0/http/server.ts", "googleapis" = "https://esm.sh/googleapis@126.0.1" }

[functions.smtp-sender]
verify_jwt = true

[functions.test-smtp]
verify_jwt = false
