
project_id = "ndhakvhrrkczgylcmyoc"

[api]
enabled = true

[db]
enable_experimental_postgres_options = true
shadow_database_flag = false

[realtime]
enabled = true

[storage]
enabled = true

[edge_functions]
enabled = true

[edge_functions.process-webhook]
verify_jwt = false

[edge_functions.cardcom-webhook]
verify_jwt = false

[edge_functions.process-unprocessed-webhooks]
verify_jwt = false
