
project_id = "ndhakvhrrkczgylcmyoc"

[api]
enabled = true
port = 54321
swagger_ui = true
openapi_url = "/rest/v1/swagger.json"

[functions]
[functions.ai-chatbot]
verify_jwt = true

[functions.financial-news]
verify_jwt = true

[functions.generate-insight]
verify_jwt = true

[functions.cardcom-payment]
verify_jwt = false

[functions.cancel-subscription]
verify_jwt = true

[functions.generate-document]
verify_jwt = true

[functions.get-cancellation-data]
verify_jwt = true

[functions.recover-payment-session]
verify_jwt = false

[functions."recover-payment-session/get-session"]
verify_jwt = false

[functions."recover-payment-session/save-session"]
verify_jwt = false

[functions.iframe-redirect]
verify_jwt = false


