
# This file defines configuration for the edge functions

# Project ID (required first line)
project_id = "ndhakvhrrkczgylcmyoc"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[functions]
[functions.cardcom-payment]
verify_jwt = false
[functions.cardcom-webhook]
verify_jwt = false
[functions.cardcom-recurring]
verify_jwt = false
[functions.cardcom-submit]
verify_jwt = false
[functions.cardcom-status]
verify_jwt = false
