
project_id = "ndhakvhrrkczgylcmyoc"

[api]
enabled = true
port = 54321

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324

[storage]
port = 54325

[functions]
port = 54326

[functions.cardcom-payment]
verify_jwt = false

[functions.cardcom-redirect]
verify_jwt = false

[functions.cardcom-status]
verify_jwt = false

[functions.cardcom-webhook]
verify_jwt = false

[functions.cardcom-iframe]
verify_jwt = false

[auth]
site_url = "http://localhost:3000"
