
project_id = "ndhakvhrrkczgylcmyoc"
[api]
enabled = true
[auth]
enabled = true
[realtime]
enabled = false
[storage]
enabled = false
[edge_functions]
[edge_functions.cardcom-status]
verify_jwt = false
