
project_id = "ndhakvhrrkczgylcmyoc"

[api]
enabled = true
port = 54321
swagger_ui = true
openapi_url = "/rest/v1/swagger.json"

[functions]
[functions.ai-chatbot]
verify_jwt = true

[functions.financial-news]
verify_jwt = true

[functions.generate-insight]
verify_jwt = true

[functions.cardcom-payment]
verify_jwt = false

[functions.cancel-subscription]
verify_jwt = true

[functions.generate-document]
verify_jwt = true

