
project_id = "ndhakvhrrkczgylcmyoc"

[api]
enabled = true
port = 54321
schemas = []

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
port = 54325

[auth]
enabled = true
port = 54326

[analytics]
enabled = true
port = 54327

[realtime]
enabled = true
port = 54328

[functions]
[functions.direct-payment]
verify_jwt = false

[functions.cardcom-payment]
verify_jwt = false

[functions.stock-data]
verify_jwt = false

[functions.smtp-sender]
verify_jwt = false
