
project_id = "ndhakvhrrkczgylcmyoc"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1"

[auth]
enabled = true
site_url = "http://127.0.0.1:5173"
uri_allow_list = ["https://ndhakvhrrkczgylcmyoc.lovable.dev", "http://localhost:5173"]
redirect_urls = ["https://ndhakvhrrkczgylcmyoc.lovable.dev/callback", "http://localhost:5173/callback"]

[functions]
[functions.reprocess-webhook-by-email]
verify_jwt = false
