
name: Lighthouse CI

on:
  push:
    branches: [main]
  schedule:
    # Run weekly on Monday at 2 AM
    - cron: '0 2 * * 1'
  workflow_dispatch: # Allow manual triggering

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci
        
      - name: Build project
        run: npm run build
        
      - name: Start static server
        run: npx serve dist &
        
      - name: Wait for server
        run: sleep 5
        
      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v10
        with:
          uploadArtifacts: true
          temporaryPublicStorage: true
          configPath: './lighthouse.config.js'
          runs: 3
          urls: |
            http://localhost:3000/
            http://localhost:3000/dashboard
            http://localhost:3000/trade-journal
            http://localhost:3000/subscription
            http://localhost:3000/courses
            
      - name: Save results as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: lighthouse-results
          path: '.lighthouseci'
